import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {productSwitcherItem} from './src/sidebar/productSwitcher';

/**
 * 智能问数（KnowFlow Analytics）文档侧边栏。
 *
 * 目录结构由 `analytics-docs/` 自动生成，顶部插入产品切换器。
 */
const sidebars: SidebarsConfig = {
  analyticsSidebar: [
    productSwitcherItem('analytics'),
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
