import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {productSwitcherItem} from './src/sidebar/productSwitcher';

/**
 * 企业知识库文档侧边栏。
 *
 * 目录结构由 `docs/` 自动生成，顶部插入产品切换器（默认停留在知识库）。
 * 各分类的排序与标题通过 `_category_.json` 控制。
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    productSwitcherItem('knowledge-base'),
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
